# Generated by Django 5.2.3 on 2025-06-21 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='Chọn ngày đầu tháng')),
                ('electricity', models.PositiveIntegerField(help_text='Số ký điện(Kw)')),
                ('water', models.PositiveIntegerField(help_text='Số nước (m³)')),
                ('electricity_rate', models.DecimalField(decimal_places=2, default=3000, max_digits=6)),
                ('water_rate', models.DecimalField(decimal_places=2, default=15000, max_digits=6)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.room')),
            ],
        ),
    ]
