# Generated by Django 5.2.3 on 2025-06-21 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='electricity',
            field=models.PositiveIntegerField(help_text='Số ký điện (kWh)'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='water_rate',
            field=models.DecimalField(decimal_places=2, default=15000, max_digits=8),
        ),
    ]
