# Generated by Django 5.2.3 on 2025-06-20 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenant',
            old_name='start_day',
            new_name='start_date',
        ),
    ]
